version: "3.9"

services:
  backend:
    image: trong2005/blog-backend:latest
    container_name: backend
    env_file:
      - .env
    environment:
      - DBMS_URL_DEV=${DB_URL}
      - DBMS_USERNAME_DEV=${DB_USERNAME}
      - DBMS_PASSWORD_DEV=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - CLIENT_ID_DEV=${GOOGLE_CLIENT_ID}
      - CLIENT_SECRET_DEV=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI_DEV=${GOOGLE_REDIRECT_URI}
      - SIGNER_KEY_ACCESS_DEV=${JWT_SIGNER_ACCESS}
      - SIGNER_KEY_REFRESH_DEV=${JWT_SIGNER_REFRESH}
      - FILE_BASE_URL=${FILE_BASE_URL}
    networks:
      - blog-net
    restart: always

  frontend:
    image: trong2005/blog-frontend:latest
    container_name: frontend
    volumes:
      - frontend_dist:/app/dist
    networks:
      - blog-net
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./webroot:/var/www/certbot
      - ./nginx/html:/usr/share/nginx/html
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - blog-net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;"
    networks:
      - blog-net
    restart: always

networks:
  blog-net:
    driver: bridge

volumes:
  frontend_dist: