version: "3.9"

services:
  backend:
    image: trong2005/blog-backend:latest
    container_name: backend
    env_file:
      - .env
    environment:
      - DBMS_URL_DEV=${DB_URL}
      - DBMS_USERNAME_DEV=${DB_USERNAME}
      - DBMS_PASSWORD_DEV=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SIGNER_KEY_ACCESS_DEV=${JWT_SIGNER_ACCESS}
      - SIGNER_KEY_REFRESH_DEV=${JWT_SIGNER_REFRESH}
      - CLIENT_ID_DEV=${GOOGLE_CLIENT_ID}
      - CLIENT_SECRET_DEV=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI_DEV=${GOOGLE_REDIRECT_URI}
    volumes:
      - uploads:/app/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - blog-net
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: trong2005/blog-frontend:latest  # FE đã build + Nginx trong image
    container_name: frontend
    depends_on:
      - backend
    networks:
      - blog-net
    restart: always
    ports:
      - "80:80"
      - "443:443"

  mysql:
    image: mysql:innovation-oracle
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_HOST=%  
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - blog-net
    restart: always

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - blog-net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;"
    networks:
      - blog-net
    restart: always

volumes:
  mysqldata:
  uploads:

networks:
  blog-net:
    driver: bridge
