# HTTP → HTTPS redirect & Certbot challenge
server {
    listen 80;
    server_name blog-test-trong.duckdns.org;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Chuyển hướng tất cả HTTP sang HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl;
    server_name blog-test-trong.duckdns.org;

    ssl_certificate     /etc/ssl/private/live/blog-test-trong.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/live/blog-test-trong.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 500M;

    # FRONTEND React build
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;  # Bắt buộc cho React Router
    }

    # BACKEND
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # UPLOADS
    location /api/uploads/ {
        proxy_pass http://backend:8080/api/uploads/;
    }

    # Cache static
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}

